In [74]:
! pip install yfinance --upgrade --no-cache-dir

Requirement already satisfied: yfinance in /usr/local/lib/python3.10/dist-packages (0.2.37)
Requirement already satisfied: pandas>=1.3.0 in /usr/local/lib/python3.10/dist-packages (from yfinance) (1.5.3)
Requirement already satisfied: numpy>=1.16.5 in /usr/local/lib/python3.10/dist-packages (from yfinance) (1.25.2)
Requirement already satisfied: requests>=2.31 in /usr/local/lib/python3.10/dist-packages (from yfinance) (2.31.0)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.10/dist-packages (from yfinance) (0.0.11)
Requirement already satisfied: lxml>=4.9.1 in /usr/local/lib/python3.10/dist-packages (from yfinance) (4.9.4)
Requirement already satisfied: appdirs>=1.4.4 in /usr/local/lib/python3.10/dist-packages (from yfinance) (1.4.4)
Requirement already satisfied: pytz>=2022.5 in /usr/local/lib/python3.10/dist-packages (from yfinance) (2023.4)
Requirement already satisfied: frozendict>=2.3.4 in /usr/local/lib/python3.10/dist-packages (from yfinance) (2.4.0)
Requirement already satisfied: peewee>=3.16.2 in /usr/local/lib/python3.10/dist-packages (from yfinance) (3.17.1)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /usr/local/lib/python3.10/dist-packages (from yfinance) (4.12.3)
Requirement already satisfied: html5lib>=1.1 in /usr/local/lib/python3.10/dist-packages (from yfinance) (1.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (2.5)
Requirement already satisfied: six>=1.9 in /usr/local/lib/python3.10/dist-packages (from html5lib>=1.1->yfinance) (1.16.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.10/dist-packages (from html5lib>=1.1->yfinance) (0.5.1)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.3.0->yfinance) (2.8.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.31->yfinance) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.31->yfinance) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.31->yfinance) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.31->yfinance) (2024.2.2)

In [75]:
import yfinance as yf
import pandas as pd

In [76]:
tickerslist = ['MSFT', 'AAPL', 'NVDA', 'GOOG', '2222.SR', 'AMZN', 'META', 'BRK-B', 'TSLA', 'V', 'MA', 'COST', 'CRM', 'BAC', 'KO']
tickers = yf.Tickers("MSFT AAPL NVDA GOOG 2222.SR AMZN META BRK-B TSLA V MA COST CRM BAC KO")

In [77]:
hist = tickers.history(period="5y")
hist.to_csv('stock-history', encoding='utf-8')

[*********************100%%**********************]  15 of 15 completed

In [78]:
hist

Price           Close                                                 \
Ticker        2222.SR        AAPL        AMZN        BAC       BRK-B
Date
2019-03-25        NaN   45.424953   88.712997  23.718573  199.440002
2019-03-26        NaN   44.955627   89.188004  24.045538  200.619995
2019-03-27        NaN   45.359962   88.285004  23.886477  199.210007
2019-03-28        NaN   45.420132   88.670998  24.151583  200.660004
2019-03-29        NaN   45.716160   89.037498  24.381348  200.889999
...               ...         ...         ...        ...         ...
2024-03-18  31.100000  173.720001  174.479996  36.009998  408.410004
2024-03-19  31.400000  176.080002  175.899994  36.029999  411.760010
2024-03-20  31.200001  178.669998  178.149994  36.750000  416.109985
2024-03-21  31.200001  171.369995  178.149994  37.509998  413.779999
2024-03-22        NaN  172.279999  178.869995  37.049999  411.600006

Price                                                                  ...  \
Ticker            COST         CRM        GOOG         KO          MA  ...
Date                                                                   ...
2019-03-25  217.190506  160.670120   59.650002  39.406006  224.149170  ...
2019-03-26  219.115250  159.192047   59.230999  39.928226  226.941101  ...
2019-03-27  219.426849  154.917633   58.651001  39.902546  226.192062  ...
2019-03-28  221.085770  154.977554   58.424500  39.876858  228.468384  ...
2019-03-29  221.929001  158.163391   58.665501  40.116562  229.042282  ...
...                ...         ...         ...        ...         ...  ...
2024-03-18  731.539978  300.510010  148.479996  60.130001  478.890015  ...
2024-03-19  732.169983  301.450012  147.919998  60.230000  484.000000  ...
2024-03-20  740.719971  306.079987  149.679993  60.750000  488.040009  ...
2024-03-21  742.559998  308.390015  148.740005  60.470001  488.640015  ...
2024-03-22  734.799988  307.769989  151.770004  60.490002  481.670013  ...

Price          Volume                                                \
Ticker           COST        CRM        GOOG          KO         MA
Date
2019-03-25  1357100.0  3795400.0  29936000.0  11668200.0  3506500.0
2019-03-26  1193000.0  6910300.0  38024000.0  11434900.0  3046900.0
2019-03-27  1351200.0  8218700.0  28004000.0  11543600.0  2640700.0
2019-03-28  1396700.0  4424800.0  19234000.0  11121100.0  2712100.0
2019-03-29  1968000.0  4913100.0  25398000.0  16045600.0  3453900.0
...               ...        ...         ...         ...        ...
2024-03-18  1595200.0  5240500.0  47676700.0  15856700.0  2072300.0
2024-03-19  1322700.0  3329900.0  17748400.0  15030600.0  2049500.0
2024-03-20  1398700.0  4946600.0  17730000.0  15258800.0  1691100.0
2024-03-21  2106900.0  6083900.0  19843900.0  13067100.0  2580300.0
2024-03-22  1791200.0  3779000.0  19226300.0  11501400.0  2277300.0

Price
Ticker            META        MSFT        NVDA         TSLA           V
Date
2019-03-25  12631200.0  27067100.0  52521200.0  153225000.0   7568000.0
2019-03-26  15437900.0  26097700.0  70350800.0  110263500.0  15594400.0
2019-03-27  10620300.0  22733400.0  47437200.0  131688000.0  12253800.0
2019-03-28  10443000.0  18334800.0  48026400.0  101611500.0  16902200.0
2019-03-29  13455500.0  25399800.0  45689600.0   89869500.0  12164400.0
...                ...         ...         ...          ...         ...
2024-03-18  11755300.0  20106000.0  66897600.0  108214400.0   4095600.0
2024-03-19  10903100.0  19837900.0  67217100.0   77271400.0   6595200.0
2024-03-20  11711100.0  17860100.0  47906300.0   83846700.0   6105000.0
2024-03-21   9712500.0  21296200.0  48037200.0   73178000.0   5057600.0
2024-03-22   8117000.0  17636500.0  58521500.0   75454700.0   8743000.0

[1505 rows x 105 columns]

In [79]:
dfs = []
tickers.tickers

{'MSFT': yfinance.Ticker object <MSFT>,
 'AAPL': yfinance.Ticker object <AAPL>,
 'NVDA': yfinance.Ticker object <NVDA>,
 'GOOG': yfinance.Ticker object <GOOG>,
 '2222.SR': yfinance.Ticker object <2222.SR>,
 'AMZN': yfinance.Ticker object <AMZN>,
 'META': yfinance.Ticker object <META>,
 'BRK-B': yfinance.Ticker object <BRK-B>,
 'TSLA': yfinance.Ticker object <TSLA>,
 'V': yfinance.Ticker object <V>,
 'MA': yfinance.Ticker object <MA>,
 'COST': yfinance.Ticker object <COST>,
 'CRM': yfinance.Ticker object <CRM>,
 'BAC': yfinance.Ticker object <BAC>,
 'KO': yfinance.Ticker object <KO>}

In [80]:
for ticker in tickerslist:
    t = yf.Ticker(ticker)
    data = t.quarterly_cashflow
    if data is not None:  # Some tickers may not have quarterly cash flow data
        data['Ticker'] = ticker  # Add a column for the ticker symbol
        dfs.append(data)

        # Fetch earnings dates
        earnings_dates = t.get_earnings_dates(limit=16)
        if earnings_dates is not None:
            earnings_df = pd.DataFrame(earnings_dates, columns=['Earnings Dates'])
            earnings_df['Ticker'] = ticker
            dfs.append(earnings_df)

In [81]:
combined_df = pd.concat(dfs)

combined_df.reset_index(inplace=True)

In [82]:
combined_df

,index,2023-12-31 00:00:00,2023-09-30 00:00:00,2023-06-30 00:00:00,2023-03-31 00:00:00,2022-12-31 00:00:00,Ticker,Earnings Dates,2024-01-31 00:00:00,2023-10-31 00:00:00,2023-07-31 00:00:00,2023-04-30 00:00:00,2023-01-31 00:00:00,2024-02-29 00:00:00,2023-11-30 00:00:00,2023-08-31 00:00:00,2023-05-31 00:00:00,2023-02-28 00:00:00
0,Free Cash Flow,9118000000.0,20666000000.0,19827000000.0,17834000000.0,4899000000.0,MSFT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Repurchase Of Capital Stock,-4000000000.0,-4831000000.0,-5704000000.0,-5509000000.0,-5459000000.0,MSFT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Repayment Of Debt,-2916000000.0,-1500000000.0,-1000000000.0,0.0,-750000000.0,MSFT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Issuance Of Debt,10773000000.0,25765000000.0,NaN,NaN,0.0,MSFT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Issuance Of Capital Stock,261000000.0,685000000.0,512000000.0,536000000.0,243000000.0,MSFT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
970,2022-04-25 06:00:00-04:00,NaN,NaN,NaN,NaN,NaN,KO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
971,2022-02-10 06:00:00-05:00,NaN,NaN,NaN,NaN,NaN,KO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
972,2021-10-27 06:00:00-04:00,NaN,NaN,NaN,NaN,NaN,KO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
973,2021-07-21 06:00:00-04:00,NaN,NaN,NaN,NaN,NaN,KO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
974,2021-04-19 06:00:00-04:00,NaN,NaN,NaN,NaN,NaN,KO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [83]:
combined_df.to_csv('combined-quarterly', encoding='utf-8')

In [84]:
# tickers.tickers['NVDA'].get_earnings_dates(limit=16)
# tickers.tickers['NVDA'].news